name: Android Build
on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4 # Aktualisiert auf v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4 # Aktualisiert auf v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build APK
        run: chmod +x gradlew && ./gradlew assembleRelease 

      - name: Upload APK
        uses: actions/upload-artifact@v4 # Aktualisiert auf v4 (Wichtig!)
        with:
          name: my-app-apk
          path: app/build/outputs/apk/release/*.apk
